mongoDatabase:
  name: test
  username: uid
  password: pwd
  connections:
    - host: localhost
      port: 27017

oauthConfig:
  clientId: <client id>
  clientSecret: <client secret>
  authorizeEndpoint: https://github.com/login/oauth/authorize
  accessTokenEndpoint: https://github.com/login/oauth/access_token
  userEndpoint: https://api.github.com/user
  idTokenIssuer: https://sam.atg.se
  idTokenSignKey: topsecret
  origin: http://localhost:8080

authenticationCachePolicy: maximumSize=1000, expireAfterAccess=30m

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logRequests: false
jerseyClientConfig:
  gzipEnabled: true
  gzipEnabledForRequests: true
  timeout: 2s
  connectionTimeout: 2s
  connectionRequestTimeout: 2s

logging:
  level: INFO
  loggers:
    se.atg: DEBUG
    io.swagger: INFO
    org.mongodb: INFO
    org.reflections: INFO
    javax.management: INFO
    org.eclipse.jetty: INFO
    org.glassfish.jersey: INFO
    org.hibernate.validator: INFO
  appenders:
    - type: console
