mongoDatabase:
  name: test
  connections:
    - host: 127.0.0.1
      port: 27017

oauthConfig:
  clientId: ${OAUTH_CLIENT_ID}
  clientSecret: ${OAUTH_CLIENT_SECRET}
  authorizeEndpoint: Not requried for tests
  accessTokenEndpoint: Not requried for tests
  userEndpoint: Not requried for tests
  idTokenIssuer: https://sam.atg.se
  idTokenSignKey: topsecret
  origin: Not required for tests

testEndpoint: http://localhost:8080/services/

logRequests: false
jerseyClientConfig:
  gzipEnabled: true
  gzipEnabledForRequests: true
  timeout: 1s
  connectionTimeout: 1s
  connectionRequestTimeout: 1s

logging:
  level: INFO
  loggers:
    se.atg: INFO
    org.mongodb: INFO
