mongoDatabase:
  name: test
  username: uid
  password: pwd
  connections:
    - host: localhost
      port: 27017

oauthConfig:
  clientId: <client id>
  clientSecret: <client secret>
  accessTokenEndpoint: https://github.hh.atg.se/login/oauth/access_token
  userEndpoint: https://github.hh.atg.se/api/v3/user
  idTokenIssuer: https://sam.hh.atg.se
  idTokenSignKey: topsecret

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logRequests: false
jerseyClientConfig:
  gzipEnabled: true
  gzipEnabledForRequests: true
  timeout: 2s
  connectionTimeout: 2s
  connectionRequestTimeout: 2s

logging:
  level: INFO
  loggers:
    se.atg: TRACE
    io.swagger: INFO
    org.mongodb: INFO
  appenders:
    - type: console
