mongoDB:
  dbName: test
  username: uid
  password: pwd
  connections:
    - host: localhost
      port: 27017

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    se.atg: TRACE
    io.swagger: INFO
    org.mongodb: INFO
  appenders:
    - type: console
