export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const OPEN_META = 'OPEN_META';
export const CLOSE_META = 'CLOSE_META';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_RESPONSE = 'SIGNIN_RESPONSE';

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const SIGNOUT_RESPONSE = 'SIGNOUT_RESPONSE';

export const SIGNIN_WINDOW_OPEN = 'SIGNIN_WINDOW_OPEN';
export const SIGNIN_WINDOW_CLOSE = 'SIGNIN_WINDOW_CLOSE';
export const SIGNIN_WINDOW_CLOSED = 'SIGNIN_WINDOW_CLOSED';

export const SIGNIN_IFRAME_REQUEST = 'SIGNIN_IFRAME_REQUEST';
export const SIGNIN_IFRAME_RESPONSE = 'SIGNIN_IFRAME_RESPONSE';

export const SIGNIN_CODE_MESSAGE = 'SIGNIN_CODE_MESSAGE';

export const VERIFY_OAUTH_CODE = 'VERIFY_OAUTH_CODE';

export const NOTIFICATION = 'NOTIFICATION';

export const FETCH_APPLICATION_LIST_REQUEST = 'FETCH_APPLICATION_LIST_REQUEST';
export const FETCH_APPLICATION_LIST_RESPONSE = 'FETCH_APPLICATION_LIST_RESPONSE';

export const FETCH_APPLICATION_REQUEST = 'FETCH_APPLICATION_REQUEST';
export const FETCH_APPLICATION_RESPONSE = 'FETCH_APPLICATION_RESPONSE';

export const FETCH_APPLICATION_DEPLOYMENTS_RESPONSE = 'FETCH_APPLICATION_DEPLOYMENTS_RESPONSE';

export const PATCH_APPLICATION_REQUEST = 'PATCH_APPLICATION_REQUEST';
export const PATCH_APPLICATION_RESPONSE = 'PATCH_APPLICATION_RESPONSE';

export const CREATE_APPLICATION_REQUEST = 'CREATE_APPLICATION_REQUEST';
export const CREATE_APPLICATION_RESPONSE = 'CREATE_APPLICATION_RESPONSE';

export const DELETE_APPLICATION_REQUEST = 'DELETE_APPLICATION_REQUEST';
export const DELETE_APPLICATION_RESPONSE = 'DELETE_APPLICATION_RESPONSE';

export const FETCH_SERVER_LIST_REQUEST = 'FETCH_SERVER_LIST_REQUEST';
export const FETCH_SERVER_LIST_RESPONSE = 'FETCH_SERVER_LIST_RESPONSE';

export const FETCH_SERVER_REQUEST = 'FETCH_SERVER_REQUEST';
export const FETCH_SERVER_RESPONSE = 'FETCH_SERVER_RESPONSE';

export const PATCH_SERVER_REQUEST = 'PATCH_SERVER_REQUEST';
export const PATCH_SERVER_RESPONSE = 'PATCH_SERVER_RESPONSE';

export const CREATE_SERVER_REQUEST = 'CREATE_SERVER_REQUEST';
export const CREATE_SERVER_RESPONSE = 'CREATE_SERVER_RESPONSE';

export const DELETE_SERVER_REQUEST = 'DELETE_SERVER_REQUEST';
export const DELETE_SERVER_RESPONSE = 'DELETE_SERVER_RESPONSE';

export const FETCH_GROUP_LIST_REQUEST = 'FETCH_GROUP_LIST_REQUEST';
export const FETCH_GROUP_LIST_RESPONSE = 'FETCH_GROUP_LIST_RESPONSE';

export const FETCH_GROUP_REQUEST = 'FETCH_GROUP_REQUEST';
export const FETCH_GROUP_RESPONSE = 'FETCH_GROUP_RESPONSE';

export const FETCH_GROUP_TAG_REQUEST = 'FETCH_GROUP_TAG_REQUEST';
export const FETCH_GROUP_TAG_RESPONSE = 'FETCH_GROUP_TAG_RESPONSE';

export const FETCH_GROUP_ID_REQUEST = 'FETCH_GROUP_ID_REQUEST';
export const FETCH_GROUP_ID_RESPONSE = 'FETCH_GROUP_ID_RESPONSE';

export const PATCH_GROUP_REQUEST = 'PATCH_GROUP_REQUEST';
export const PATCH_GROUP_RESPONSE = 'PATCH_GROUP_RESPONSE';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_RESPONSE = 'CREATE_GROUP_RESPONSE';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_RESPONSE = 'DELETE_GROUP_RESPONSE';

export const ADD_SUBGROUP_REQUEST = 'ADD_SUBGROUP_REQUEST';
export const ADD_SUBGROUP_RESPONSE = 'ADD_SUBGROUP_RESPONSE';

export const REMOVE_SUBGROUP_REQUEST = 'REMOVE_SUBGROUP_REQUEST';
export const REMOVE_SUBGROUP_RESPONSE = 'REMOVE_SUBGROUP_RESPONSE';

export const FETCH_ASSET_LIST_REQUEST = 'FETCH_ASSET_LIST_REQUEST';
export const FETCH_ASSET_LIST_RESPONSE = 'FETCH_ASSET_LIST_RESPONSE';

export const FETCH_ASSET_REQUEST = 'FETCH_ASSET_REQUEST';
export const FETCH_ASSET_RESPONSE = 'FETCH_ASSET_RESPONSE';

export const PATCH_ASSET_REQUEST = 'PATCH_ASSET_REQUEST';
export const PATCH_ASSET_RESPONSE = 'PATCH_ASSET_RESPONSE';

export const CREATE_ASSET_REQUEST = 'CREATE_ASSET_REQUEST';
export const CREATE_ASSET_RESPONSE = 'CREATE_ASSET_RESPONSE';

export const DELETE_ASSET_REQUEST = 'DELETE_ASSET_REQUEST';
export const DELETE_ASSET_RESPONSE = 'DELETE_ASSET_RESPONSE';

export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_RESPONSE = 'FETCH_SEARCH_RESPONSE';

export const FETCH_INFO_REQUEST = 'FETCH_INFO_REQUEST';
export const FETCH_INFO_RESPONSE = 'FETCH_INFO_RESPONSE';

export const FETCH_RELEASE_NOTES_REQUEST = 'FETCH_RELEASE_NOTES_REQUEST';
export const FETCH_RELEASE_NOTES_RESPONSE = 'FETCH_RELEASE_NOTES_RESPONSE';
