export const FETCH_APPLICATION_LIST_REQUEST = 'FETCH_APPLICATION_LIST_REQUEST';
export const FETCH_APPLICATION_LIST_RESPONSE = 'FETCH_APPLICATION_LIST_RESPONSE';

export const FETCH_APPLICATION_REQUEST = 'FETCH_APPLICATION_REQUEST';
export const FETCH_APPLICATION_RESPONSE = 'FETCH_APPLICATION_RESPONSE';

export const FETCH_SERVER_LIST_REQUEST = 'FETCH_SERVER_LIST_REQUEST';
export const FETCH_SERVER_LIST_RESPONSE = 'FETCH_SERVER_LIST_RESPONSE';

export const FETCH_SERVER_REQUEST = 'FETCH_SERVER_REQUEST';
export const FETCH_SERVER_RESPONSE = 'FETCH_SERVER_RESPONSE';

export const FETCH_GROUP_LIST_REQUEST = 'FETCH_GROUP_LIST_REQUEST';
export const FETCH_GROUP_LIST_RESPONSE = 'FETCH_GROUP_LIST_RESPONSE';

export const FETCH_GROUP_REQUEST = 'FETCH_GROUP_REQUEST';
export const FETCH_GROUP_RESPONSE = 'FETCH_GROUP_RESPONSE';

export const FETCH_ASSET_LIST_REQUEST = 'FETCH_ASSET_LIST_REQUEST';
export const FETCH_ASSET_LIST_RESPONSE = 'FETCH_ASSET_LIST_RESPONSE';

export const FETCH_ASSET_REQUEST = 'FETCH_ASSET_REQUEST';
export const FETCH_ASSET_RESPONSE = 'FETCH_ASSET_RESPONSE';

export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_RESPONSE = 'FETCH_SEARCH_RESPONSE';

export const FETCH_INFO_REQUEST = 'FETCH_INFO_REQUEST';
export const FETCH_INFO_RESPONSE = 'FETCH_INFO_RESPONSE';

export const FETCH_RELEASE_NOTES_REQUEST = 'FETCH_RELEASE_NOTES_REQUEST';
export const FETCH_RELEASE_NOTES_RESPONSE = 'FETCH_RELEASE_NOTES_RESPONSE';
