export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';

export const OPEN_META = 'OPEN_META';
export const CLOSE_META = 'CLOSE_META';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';

export const NOTIFICATION = 'NOTIFICATION';

export const FETCH_APPLICATION_LIST_REQUEST = 'FETCH_APPLICATION_LIST_REQUEST';
export const FETCH_APPLICATION_LIST_RESPONSE = 'FETCH_APPLICATION_LIST_RESPONSE';

export const FETCH_APPLICATION_REQUEST = 'FETCH_APPLICATION_REQUEST';
export const FETCH_APPLICATION_RESPONSE = 'FETCH_APPLICATION_RESPONSE';

export const FETCH_APPLICATION_DEPLOYMENTS_RESPONSE = 'FETCH_APPLICATION_DEPLOYMENTS_RESPONSE';

export const PATCH_APPLICATION_REQUEST = 'PATCH_APPLICATION_REQUEST';
export const PATCH_APPLICATION_RESPONSE = 'PATCH_APPLICATION_RESPONSE';

export const CREATE_APPLICATION_REQUEST = 'CREATE_APPLICATION_REQUEST';
export const CREATE_APPLICATION_RESPONSE = 'CREATE_APPLICATION_RESPONSE';

export const FETCH_SERVER_LIST_REQUEST = 'FETCH_SERVER_LIST_REQUEST';
export const FETCH_SERVER_LIST_RESPONSE = 'FETCH_SERVER_LIST_RESPONSE';

export const FETCH_SERVER_REQUEST = 'FETCH_SERVER_REQUEST';
export const FETCH_SERVER_RESPONSE = 'FETCH_SERVER_RESPONSE';

export const PATCH_SERVER_REQUEST = 'PATCH_SERVER_REQUEST';
export const PATCH_SERVER_RESPONSE = 'PATCH_SERVER_RESPONSE';

export const FETCH_GROUP_LIST_REQUEST = 'FETCH_GROUP_LIST_REQUEST';
export const FETCH_GROUP_LIST_RESPONSE = 'FETCH_GROUP_LIST_RESPONSE';

export const FETCH_GROUP_REQUEST = 'FETCH_GROUP_REQUEST';
export const FETCH_GROUP_RESPONSE = 'FETCH_GROUP_RESPONSE';

export const FETCH_GROUP_TAG_REQUEST = 'FETCH_GROUP_TAG_REQUEST';
export const FETCH_GROUP_TAG_RESPONSE = 'FETCH_GROUP_TAG_RESPONSE';

export const FETCH_GROUP_ID_REQUEST = 'FETCH_GROUP_ID_REQUEST';
export const FETCH_GROUP_ID_RESPONSE = 'FETCH_GROUP_ID_RESPONSE';

export const PATCH_GROUP_REQUEST = 'PATCH_GROUP_REQUEST';
export const PATCH_GROUP_RESPONSE = 'PATCH_GROUP_RESPONSE';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_RESPONSE = 'CREATE_GROUP_RESPONSE';

export const ADD_SUBGROUP_REQUEST = 'ADD_SUBGROUP_REQUEST';
export const ADD_SUBGROUP_RESPONSE = 'ADD_SUBGROUP_RESPONSE';

export const REMOVE_SUBGROUP_REQUEST = 'REMOVE_SUBGROUP_REQUEST';
export const REMOVE_SUBGROUP_RESPONSE = 'REMOVE_SUBGROUP_RESPONSE';

export const FETCH_ASSET_LIST_REQUEST = 'FETCH_ASSET_LIST_REQUEST';
export const FETCH_ASSET_LIST_RESPONSE = 'FETCH_ASSET_LIST_RESPONSE';

export const FETCH_ASSET_REQUEST = 'FETCH_ASSET_REQUEST';
export const FETCH_ASSET_RESPONSE = 'FETCH_ASSET_RESPONSE';

export const PATCH_ASSET_REQUEST = 'PATCH_ASSET_REQUEST';
export const PATCH_ASSET_RESPONSE = 'PATCH_ASSET_RESPONSE';

export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_RESPONSE = 'FETCH_SEARCH_RESPONSE';

export const FETCH_INFO_REQUEST = 'FETCH_INFO_REQUEST';
export const FETCH_INFO_RESPONSE = 'FETCH_INFO_RESPONSE';

export const FETCH_RELEASE_NOTES_REQUEST = 'FETCH_RELEASE_NOTES_REQUEST';
export const FETCH_RELEASE_NOTES_RESPONSE = 'FETCH_RELEASE_NOTES_RESPONSE';
